# Generated by Django 3.2.14 on 2022-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(null=True, verbose_name='время отправки'),
        ),
    ]
