# Generated by Django 3.2.14 on 2022-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_message_sending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='id задачи celery'),
        ),
    ]
